[launcher]
version = 1.1.0
description = Collects DNS query stats, query logs, and top domains/clients from a Pi-hole instance via its REST API
author = Aaron Stone

[id]
version = 1.1.0
name = ta_pihole

[install]
build = 1789031085
is_configured = false
state = enabled

[package]
id = ta_pihole
check_for_updates = true

[ui]
label = piHole Add-on for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta_pihole_settings = simple
reload.ta_pihole_account = simple
