[pihole_stats_summary]
python.version = python3
python.required = 3.9, 3.13
index = default
interval = 60

[pihole_queries]
python.version = python3
python.required = 3.9, 3.13
index = default
interval = 300

[pihole_top_lists]
python.version = python3
python.required = 3.9, 3.13
index = default
interval = 300
lists_to_collect = top_domains,top_clients
top_count = 25
