[admin:ta_pihole_configuration]
match = /
members = ta_pihole_account, ta_pihole_settings

[admin:ta_pihole_inputs]
match = /
members = ta_pihole_pihole_queries, ta_pihole_pihole_stats_summary, ta_pihole_pihole_top_lists

[admin:ta_pihole_field_options]
match = /
members = ta_pihole_field_options

[admin_external:ta_pihole_account]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_pihole_settings]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:ta_pihole_pihole_stats_summary]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_pihole_stats_summary.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_pihole_pihole_queries]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_pihole_queries.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_pihole_pihole_top_lists]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_pihole_top_lists.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:ta_pihole_field_options]
handlertype = python
python.version = python3
python.required = 3.9, 3.13
handlerfile = ta_pihole_rh_field_options.py
handleractions = list
handlerpersistentmode = true
