[expose:ta_pihole_account]
pattern = ta_pihole_account
methods = POST, GET

[expose:ta_pihole_account_specified]
pattern = ta_pihole_account/*
methods = POST, GET, DELETE

[expose:ta_pihole_settings]
pattern = ta_pihole_settings
methods = POST, GET

[expose:ta_pihole_settings_specified]
pattern = ta_pihole_settings/*
methods = POST, GET, DELETE

[expose:ta_pihole_pihole_stats_summary]
pattern = ta_pihole_pihole_stats_summary
methods = POST, GET

[expose:ta_pihole_pihole_stats_summary_specified]
pattern = ta_pihole_pihole_stats_summary/*
methods = POST, GET, DELETE

[expose:ta_pihole_pihole_queries]
pattern = ta_pihole_pihole_queries
methods = POST, GET

[expose:ta_pihole_pihole_queries_specified]
pattern = ta_pihole_pihole_queries/*
methods = POST, GET, DELETE

[expose:ta_pihole_pihole_top_lists]
pattern = ta_pihole_pihole_top_lists
methods = POST, GET

[expose:ta_pihole_pihole_top_lists_specified]
pattern = ta_pihole_pihole_top_lists/*
methods = POST, GET, DELETE

[expose:ta_pihole_field_options]
pattern = ta_pihole_field_options
methods = GET

[expose:data/indexes]
pattern = data/indexes
methods = GET
